[package]
name = "pera"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]
anemo.workspace = true
anyhow.workspace = true
async-recursion.workspace = true
async-trait.workspace = true
axum.workspace = true
bcs.workspace = true
bin-version.workspace = true
bip32.workspace = true
camino.workspace = true
clap.workspace = true
datatest-stable.workspace = true
futures.workspace = true
http.workspace = true
im.workspace = true
inquire.workspace = true
insta.workspace = true
json_to_table.workspace = true
miette.workspace = true
num-bigint.workspace = true
prometheus.workspace = true
rand.workspace = true
regex.workspace = true
reqwest.workspace = true
rusoto_core.workspace = true
rusoto_kms.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
serde.workspace = true
shlex.workspace = true
signature.workspace = true
tabled.workspace = true
tap.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
diesel.workspace = true
uuid.workspace = true
url.workspace = true

pera-config.workspace = true
pera-bridge.workspace = true
pera-cluster-test.workspace = true
pera-execution = { path = "../../pera-execution" }
pera-faucet.workspace = true
pera-swarm-config.workspace = true
pera-graphql-rpc = {workspace = true, optional = true}
pera-indexer = { workspace = true, optional = true }
pera-genesis-builder.workspace = true
pera-types.workspace = true
pera-json.workspace = true
pera-swarm.workspace = true
pera-json-rpc-types.workspace = true
pera-sdk.workspace = true
pera-keys.workspace = true
pera-source-validation.workspace = true
pera-move = { workspace = true, features = ["all"] }
pera-move-build.workspace = true
pera-package-management.workspace = true
pera-protocol-config.workspace = true
shared-crypto.workspace = true
pera-replay.workspace = true
pera-transaction-builder.workspace = true
move-binary-format.workspace = true
test-cluster.workspace = true
pera-mpc-types.workspace = true

fastcrypto.workspace = true
fastcrypto-zkp.workspace = true

rustyline.workspace = true
rustyline-derive.workspace = true
colored.workspace = true
unescape.workspace = true
shell-words.workspace = true

tempfile.workspace = true
telemetry-subscribers.workspace = true

move-analyzer.workspace = true
move-bytecode-verifier-meter.workspace = true
move-core-types.workspace = true
move-package.workspace = true
csv.workspace = true
move-vm-profiler.workspace = true
move-vm-config.workspace = true
move-command-line-common.workspace = true
rand_chacha = "0.3.1"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemalloc-ctl.workspace = true

[dev-dependencies]
prometheus.workspace = true
fs_extra.workspace = true
expect-test.workspace = true
assert_cmd.workspace = true
toml.workspace = true

test-cluster.workspace = true
pera-macros.workspace = true
pera-simulator.workspace = true
pera-test-transaction-builder.workspace = true
serde_json.workspace = true

[target.'cfg(msim)'.dependencies]
msim.workspace = true

[package.metadata.cargo-udeps.ignore]
normal = ["jemalloc-ctl"]

[[example]]
name = "generate-genesis-checkpoint"
path = "src/generate_genesis_checkpoint.rs"
test = false

[[test]]
name = "ptb_files_tests"
harness = false

[features]
gas-profiler = [
    "pera-types/gas-profiler",
    "pera-execution/gas-profiler",
]
indexer = ["dep:pera-indexer", "dep:pera-graphql-rpc"]
