[package]
name = "signature-mpc-wasm"
authors = ["dWallet Labs, Ltd. <dev@dwalletlabs.com>"]
description = "Signature MPC in WASM"
version = "0.1.6"
edition = "2021"
license = "BSD-3-Clause-Clear"
publish = false

[dependencies]
rand = { version = "0.8", features = ["std"] }
rand_core = { version = "0.6", features = ["std"] }
signature-mpc = { path = "../../crates/signature-mpc" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

wasm-bindgen = "0.2.92"
getrandom = { version = "0.2", features = ["js"] }
thiserror = "1.0"
bcs = "0.1.6"
serde-wasm-bindgen = "0.6.5"
anyhow = "1.0.86"

[lib]
crate-type = ["cdylib"]
