[package]
name = "pera-keys"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
signature.workspace = true
rand.workspace = true
tiny-bip39.workspace = true
bip32.workspace = true
slip10_ed25519.workspace = true
fastcrypto = { workspace = true, features = ["copy_key"] }
shared-crypto.workspace = true
pera-types.workspace = true
regex.workspace = true

[dev-dependencies]
tempfile.workspace = true
