# config.yaml format:

# URL of the remote store
# remote_store_url: <url>
# URL for Ethereum RPC
# eth_rpc_url: <url>
# Database connection URL
# db_url: <url>
# Path to the checkpoints
# checkpoints_path: <path>
# Number of concurrent operations
# concurrency: 1
# Bridge genesis checkpoint in PERA, for testnet = 43917829
# bridge_genesis_checkpoint: <pera bridge genesis checkpoint>
# Ethereum to Pera bridge contract address
# eth_pera_bridge_contract_address: <contract_address>
# Starting block number
# start_block: <indexing_start_block>
# Client metric URL
# metric_url: <url>
# Client metric port
# metric_port: <port>
# checkpoint size of each backfill worker, use 432000 for 1 worker per day, assume 5 checkpoint per second
# back_fill_lot_size: <backfill lot size>
# Optional starting checkpoint for realtime ingestion task
# resume_from_checkpoint: <Pera checkpoint>