[package]
name = "ika-swarm-config"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
dwallet-rng.workspace = true
dwallet-classgroups-types.workspace = true
anemo.workspace = true
anyhow.workspace = true
bcs.workspace = true
fastcrypto.workspace = true
rand = "0.8" # use old version for compatability with fastcrypto
serde.workspace = true
serde_with.workspace = true
tempfile.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["full"] }

shared-crypto.workspace = true
ika-config.workspace = true
sui-macros.workspace = true
ika-protocol-config.workspace = true
ika-types.workspace = true

sui.workspace = true
sui-config.workspace = true
sui-keys.workspace = true
sui-sdk.workspace = true
sui-types.workspace = true
ika-move-packages.workspace = true
move-core-types.workspace = true
serde_json.workspace = true
move-package.workspace = true
url.workspace = true

[target.'cfg(msim)'.dependencies]
sui-simulator.workspace = true

[dev-dependencies]
tempfile.workspace = true