[package]
name = "pera-move-natives-v0"
version = "0.1.0"
edition = "2021"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Move framework for pera platform"
license = "BSD-3-Clause-Clear"
publish = false

[dependencies]
better_any.workspace = true
bcs.workspace = true
linked-hash-map = "0.5.6"
smallvec.workspace = true

fastcrypto-zkp.workspace = true
fastcrypto.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
move-vm-types.workspace = true

move-stdlib-natives = { path = "../../../external-crates/move/move-execution/v0/crates/move-stdlib-natives", package = "move-stdlib-natives-v0" }
move-vm-runtime = { path = "../../../external-crates/move/move-execution/v0/crates/move-vm-runtime", package = "move-vm-runtime-v0" }

pera-protocol-config.workspace = true
pera-types.workspace = true
tracing.workspace = true
