[package]
name = "class_groups_constants"
edition = "2021"
version.workspace = true

[dependencies]
twopc_mpc = { git = "https://github.com/dwallet-labs/cryptography-private", branch = "pera-dkg-changes", subdir = "2pc-mpc", features = ["secp256k1", "bulletproofs", "class_groups", "paillier"] }
group = {git = "https://github.com/dwallet-labs/cryptography-private", branch = "pera-dkg-changes", subdir = "group"}
serde = "1.0.210"
bcs = "0.1.6"
hex = "0.4.3"
anyhow = "1.0.90"

[lints]
workspace = true
