[package]
name = "class_groups_constants"
edition = "2021"
version.workspace = true

[dependencies]
twopc_mpc.workspace = true
group.workspace = true
serde = "1.0.210"
bcs = "0.1.6"
hex = "0.4.3"
anyhow = "1.0.90"

[lints]
workspace = true
