[package]
name = "shared_wasm_class_groups"
edition = "2021"
version.workspace = true

[dependencies]
twopc_mpc.workspace = true
class_groups.workspace = true
mpc.workspace = true
group.workspace = true
bcs = "0.1.6"
base64.workspace = true
serde.workspace = true
schemars.workspace = true
anyhow.workspace = true
dwallet-mpc-types.workspace = true
k256.workspace = true
sha2 = "0.10.8"
sha3 = "0.10.8"
dwallet-classgroups-types.workspace = true

[lints]
workspace = true
