name: Tag

on:
  repository_dispatch:
    types: [tag-main]

  workflow_call:
    inputs:
      ika_commit:
        description: 'Ika repo commit to tag'
        type: string
        required: true
      tag_name:
        description: 'Tag Name'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      ika_commit:
        description: 'Ika repo commit to tag'
        type: string
        required: true
      tag_name:
        description: 'Tag Name'
        type: string
        required: true

env:
  IKA_COMMIT: "${{ github.event.client_payload.ika_commit || inputs.ika_commit }}"
  TAG_NAME: "${{ github.event.client_payload.tag_name || inputs.tag_name }}"

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # Pin v4.1.1

    - name: Tag
      uses: julbme/gh-action-manage-tag@v1
      with:
        name: ${{ env.TAG_NAME }}
        state: present
        from: ${{ env.IKA_COMMIT }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
